### PR TITLE
#156 - Update coupon usage in Model/Notify.php

### PR DESCRIPTION
**Pull request by walkwizus**

### CODE REVIEW

**Comment by legithubdeaymeric** [comment]
@walkwizus 

Thanks for your contribution.
We plan to add your MR on the next release.

**Comment by Synoffs** [comment]
Hello !
@walkwizus Thx for your commit
@legithubdeaymeric When this pull request will be merged please ?

**Comment by JBaptisteLvt** [comment]
Hello !
This issue is currently being handled by the dev team !
Due to security issues, we are unable to directly merge issues from github, but you will be credited in the CHANGELOG.md file once the fix ships :)

**Comment by JBaptisteLvt** [comment]
Released in 1.19.0 - 11/05/2023

**Comment by walkwizus** [comment]
> Hello ! This issue is currently being handled by the dev team ! Due to security issues, we are unable to directly merge issues from github, but you will be credited in the CHANGELOG.md file once the fix ships :)

Thanks for the credit :).

**Pull request closed without merging**
